<a href="https://colab.research.google.com/github/LeeSeungYun1020/Machine_Learning/blob/main/PyTorch_Tutorial/01_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline

# 파이토치 기본 익히기

In [2]:
import torch
import numpy as np

## 텐서

### 텐서 초기화

텐서는 numpy의 ndarray와 유사하다.
명시적으로 오버라이드하지 않으면 텐서의 속성(모양과 자료형)은 유지된다.

In [4]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
x_np = torch.from_numpy(np.array(data))
x_np

tensor([[1, 2],
        [3, 4]])

In [9]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [13]:
# 자료형이 유지되므로 float로 명시적으로 바꾸어 주어야
torch.rand_like(x_data, dtype=torch.float)

tensor([[0.3677, 0.8244],
        [0.5424, 0.5921]])

In [15]:
shape = (3, 2)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print("RAND\n", rand_tensor)
print("ONES\n", ones_tensor)
print("ZEROS\n", zeros_tensor)

RAND
 tensor([[0.0720, 0.0192],
        [0.1800, 0.3191],
        [0.8245, 0.0194]])
ONES
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
ZEROS
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


### 텐서의 속성

In [4]:
tensor = torch.rand(1, 2)
tensor

tensor([[0.7702, 0.5660]])

In [19]:
tensor.shape

torch.Size([1, 2])

In [20]:
tensor.dtype

torch.float32

In [21]:
tensor.device

device(type='cpu')

### 텐서 연산

#### GPU에서 연산 실행

In [5]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [12]:
tensor = torch.ones(4, 4)
print(tensor[0])
print(tensor[:,0])
print(tensor[..., -1])
tensor[..., -1] = 0
tensor

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])


tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

In [18]:
t1 = torch.cat([tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.],
        [1., 1., 1., 0., 1., 1., 1., 0.]])

In [17]:
t2 = torch.cat([tensor, tensor])
t2

tensor([[1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 0.]])

In [22]:
tensor=torch.tensor([[1, 2], [3, 4]])
print(tensor)

tensor([[1, 2],
        [3, 4]])


In [26]:
tensor @ tensor.T # 행렬 곱 계산
tensor.matmul(tensor.T) # 같은 연산

tensor([[ 5, 11],
        [11, 25]])

In [28]:
tensor * tensor # 요소별 곱 계산
tensor.mul(tensor) # 같은 연산

tensor([[ 1,  4],
        [ 9, 16]])

In [34]:
agg = tensor.sum()
agg_item =agg.item()
print(agg, agg_item, type(agg_item)) 
# 요소가 하나인 텐서는 item()으로 숫자값 변환됨

tensor(10) 10 <class 'int'>


In [40]:
print(tensor)
tensor.add(5)
print(tensor)
# 일반적인 연산은 파연산자에 결과가 저장되지 않음
tensor.add_(5)
print(tensor)
# in-place 연산은 _ 접미사를 가지며 피연산자의 값을 결과 값으로 변경

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[6, 7],
        [8, 9]])


In [43]:
t = torch.ones(5)
n = t.numpy()
n

array([1., 1., 1., 1., 1.], dtype=float32)

In [44]:
t.add_(1)
n
# t의 변경 사항이 n에도 반영됨!!!

array([2., 2., 2., 2., 2.], dtype=float32)

In [52]:
n = np.ones(5)
t = torch.from_numpy(n)
t

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [53]:
np.add(n, 1, out=n)
t
# n의 변경 사항이 t에도 반영됨!!!

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [54]:
t.add_(2)
n
# 서로 완전히 연동

array([4., 4., 4., 4., 4.])